FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    ninja-build \
    valgrind \
    libspdlog-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
